### ISSUE TITLE
modify the instruction

### ISSUE THREAD

**Issue by zjuchenyuan** [dtag-dev-sec/cowrie#4]
I followed as you told, cp and run as a system service...
but without a proper configuration about /data/cowrie, there will be a lot of errors:
 No such file or directory: u'/data/cowrie/keys/ssh_host_rsa_key.pub'
 exceptions.IOError: [Errno 2] No such file or directory: u'/data/cowrie/log/tty/20161109-150044-ee332b49-0i.log'

All of these problems are caused by not correctly congifure /data/cowire, here are my command to fix this:
mkdir -p /data/cowrie/downloads/
mkdir -p /data/cowrie/keys/
cp  /etc/ssh/ssh_host* /data/cowrie/keys/
mkdir -p /data/cowrie/log/tty/
mkdir -p /data/cowrie/misc/
chmod -R 777 /data/cowrie

**Comment by t3chn0m4g3** [comment]
Thank you for your feedback. Cowrie is a part of [T-Pot](https://github.com/dtag-dev-sec/tpotce) which takes care of providing the necessary folders.
