### ISSUE TITLE
cowrie/twisted version mismatch

### ISSUE THREAD

**Issue by mcfusaro** [dtag-dev-sec/cowrie#5]
A new build of the dockerized cowrie doesn't work out of the box, while  using a pre-built image from docker.io is OK.
What happens is exactly what is described in this cowrie issue:
See https://github.com/micheloosterhof/cowrie/issues/443

**Comment by t3chn0m4g3** [comment]
Nice catch! Thanks for the heads up!

**Comment by t3chn0m4g3** [comment]
this is fixed by commit # ee60f0f
